=== Helloar8/pos-2025-tarefas/xsd/definicoes.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT cardapio ( prato+ )>
<!ELEMENT prato (nome, ingredientes+, tempo_preparo, descricao, preco, calorias)>
<!ATTLIST prato id ID #REQUIRED>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT tempo_preparo (#PCDATA)>
<!ELEMENT descricao (#PCDATA)>
<!ELEMENT preco (#PCDATA)>
<!ATTLIST preco moeda (BRL|USD) "BRL">
<!ELEMENT calorias (#PCDATA)>
<!ENTITY reais "R$">

=== Helloar8/pos-2025-tarefas/parsers/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE cardapio SYSTEM "definicoes.dtd">
<cardapio>
    <prato id="p1">
        <nome>Feijoada</nome>
        <ingredientes>
            <ingrediente>Feijão preto</ingrediente>
            <ingrediente>Carnes variadas</ingrediente>
            <ingrediente>Linguiça</ingrediente>
            <ingrediente>Arroz</ingrediente>
            <ingrediente>Farinha de mandioca</ingrediente>
        </ingredientes>
        <tempo_preparo>120 min</tempo_preparo>
        <descricao>Prato tipicamente brasileiro, com o sabor inconfundível.</descricao>
        <preco >45.00</preco>
        <calorias>1200 kcal</calorias>
    </prato>

    <prato id="p2">
        <nome>Pizza Margherita</nome>
        <ingredientes>
            <ingrediente> Massa de pizza </ingrediente>
            <ingrediente>molho de tomate </ingrediente>
            <ingrediente> queijo mozzarella</ingrediente>
            <ingrediente> manjericão</ingrediente> 
        </ingredientes>
        <tempo_preparo>30 min</tempo_preparo>
        <descricao>Clássica pizza italiana com sabor fresco e leve.</descricao>
        <preco moeda="BRL">35.00</preco>
        <calorias>800 kcal</calorias>
    </prato>
    
    <prato id="p3">
        <nome>Lasagna</nome>
        <ingredientes>
            <ingrediente> massa de lasanha</ingrediente>
            <ingrediente> carne moída </ingrediente>
            <ingrediente>molho de tomate</ingrediente>
            <ingrediente> queijo </ingrediente>
        </ingredientes>
        <tempo_preparo>90 min</tempo_preparo>
        <descricao>Deliciosa lasanha com camadas de sabor.</descricao>
        <preco>50.00</preco>
        <calorias>900 kcal</calorias>
    </prato>

    <prato id= "p4">
        <nome>Sushi</nome>
        <ingredientes>
            <ingrediente> peixe cru</ingrediente>
            <ingrediente>alga nori </ingrediente>
            <ingrediente>vegetais </ingrediente>
        </ingredientes>
        <tempo_preparo>60 min</tempo_preparo>
        <descricao>Prato japonês com uma combinação de sabores únicos.</descricao>
        <preco>70.00</preco>
        <calorias>600 kcal</calorias>
    </prato>

    <prato id= "p5">
        <nome>Churrasco</nome>
        <ingredientes>
            <ingrediente> carne grelhada </ingrediente> 
            <ingrediente> farofa </ingrediente>
            <ingrediente> vinagrete </ingrediente>  
        </ingredientes>
        <tempo_preparo>180 min</tempo_preparo>
        <descricao>Tradicional churrasco brasileiro com carnes suculentas.</descricao>
        <preco>80.00</preco>
        <calorias>1500 kcal</calorias>
    </prato>
</cardapio>
